### ISSUE TITLE
Request : add minimal demo for using CSG operations

### ISSUE THREAD

**Issue by nukadelic** [sabresaurus/SabreCSG#250]
Been looking for a quick csg implementation for unity for few days now, nothing seems to be working so far, would love to see a minimal example of how to use the math part for boolean intersection preferably with result rendered mesh, cheers.

**Comment by Henry00IS** [comment]
Hey Nukadelic,

there is an entire wiki article about [Coding with SabreCSG](https://github.com/sabresaurus/SabreCSG/wiki/Tutorial-3). It also links two more tutorials at the bottom. Perhaps this is what you were looking for.

I'd also recommend checking out the new [Chisel project](https://github.com/RadicalCSG/Chisel.Prototype) and joining the [Chisel Discord](https://discord.gg/zttNkPQ). It's the new CSG level editor we are working on. One of the design goals is runtime support and it's a hundred times faster. Not production ready yet- but since you want the math part you can talk to some very knowledgeable people there.
